name: Lint
on:
  push:
    branches: [ test-sha256-hash-verification ]
  pull_request:

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: avri-schneider/setup-tflint@test-sha256-hash-verification
      name: Setup TFLint
      with:
        expected_sha256: "40f7ee2dbeb8e7cbd5ab7b10912f60eb14aa4fbff62603eeb67fdb5f7cbb794a,bf758ff29b607b3fbc4a3630ea3b39df4afafe3cdb80c6d71fe528feeac2c58e,fed6ff15ee10db34a23044ac0d4da8fdc1f2f3663b32ec85d388374dd95670aa"
        tflint_version: v0.52.0

    - name: Show version
      run: tflint --version
